apiVersion: v1
kind: Service
metadata:
  name: express-4016-service
  namespace: hwang268
spec:
  type: LoadBalancer
  selector:
    app: express-4016
  ports:
  - name: http
    port: 30000
    protocol: TCP
    targetPort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: express-4016-service
  namespace: probe
spec:
  type: NodePort
  selector:
    app: express-4016
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30010