apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: express-4016-autoscaler
 namespace: hwang268
spec:
 maxReplicas: 5
 minReplicas: 1
 scaleTargetRef:
  apiVersion: apps/v1
  kind: StatefulSet
  name: express-4016-deployment
 targetCPUUtilizationPercentage: 30